import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";

import { ThemeProvider } from "next-themes";

import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
          <Theme accentColor="blue">{children}</Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
